# Generated by Django 4.1 on 2022-09-06 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
